### ISSUE TITLE
Can't start mapproxy after installation

### ISSUE THREAD

**Issue by maraev** [baasgeo/mapproxywindows#4]
Hi!
I tried to install your packages on Win 7. When installation was finished and I started mapproxy via CMD I got this error:

[i]
C:\Users\maraev>"C:\Program Files (x86)\MapProxy-1.7.1\App\python.exe" "C:\Program Files (x86)\MapProxy-1.7.1\mapproxy_app.py"
Traceback (most recent call last):
  File "C:\Program Files (x86)\MapProxy-1.7.1\mapproxy_app.py", line 9, in <module>
    from mapproxy.wsgiapp import make_wsgi_app
  File "C:\Program Files (x86)\MapProxy-1.7.1\App\lib\site-packages\mapproxy-1.7.1-py2.7.egg\mapproxy\wsgiapp.py", line 29, in <module>
    from mapproxy.config import local_base_config
  File "C:\Program Files (x86)\MapProxy-1.7.1\App\lib\site-packages\mapproxy-1.7.1-py2.7.egg\mapproxy\config\__init__.py", line 16, in <module>
    from mapproxy.config.config import (
  File "C:\Program Files (x86)\MapProxy-1.7.1\App\lib\site-packages\mapproxy-1.7.1-py2.7.egg\mapproxy\config\config.py", line 23, in <module>
    from mapproxy.util.yaml import load_yaml_file
  File "C:\Program Files (x86)\MapProxy-1.7.1\App\lib\site-packages\mapproxy-1.7.1-py2.7.egg\mapproxy\util\yaml.py", line 17, in <module>
    import yaml
  File "C:\Program Files (x86)\MapProxy-1.7.1\App\lib\site-packages\pyyaml-3.11-py2.7-win32.egg\yaml\__init__.py", line 14, in <module>

  File "C:\Program Files (x86)\MapProxy-1.7.1\App\lib\site-packages\pyyaml-3.11-py2.7-win32.egg\yaml\cyaml.py", line 5, in <module>
  File "C:\Program Files (x86)\MapProxy-1.7.1\App\lib\site-packages\pyyaml-3.11-py2.7-win32.egg\_yaml.py", line 7, in <module>
  File "C:\Program Files (x86)\MapProxy-1.7.1\App\lib\site-packages\pyyaml-3.11-py2.7-win32.egg\_yaml.py", line 4, in __bootstrap__
  File "C:\Program Files (x86)\MapProxy-1.7.1\App\lib\site-packages\pkg_resources.py", line 882, in resource_filename
    self, resource_name
  File "C:\Program Files (x86)\MapProxy-1.7.1\App\lib\site-packages\pkg_resources.py", line 1351, in get_resource_filename
    self._extract_resource(manager, self._eager_to_zip(name))
  File "C:\Program Files (x86)\MapProxy-1.7.1\App\lib\site-packages\pkg_resources.py", line 1406, in _extract_resource
    manager.extraction_error()  # report a user-friendly error
  File "C:\Program Files (x86)\MapProxy-1.7.1\App\lib\site-packages\pkg_resources.py", line 928, in extraction_error
    raise err
pkg_resources.ExtractionError: Can't extract file(s) to egg cache

The following error occurred while trying to extract file(s) to the Python egg
cache:

  [Error 5] Access is denied: 'C:\\Users\\maraev\\AppData\\Roaming\\Python-Eggs\\pyyaml-3.11-py2.7-win32.egg-tmp\\_yaml.pyd'

The Python egg cache directory is currently set to:

  C:\Users\maraev\AppData\Roaming\Python-Eggs

Perhaps your account does not have write access to this directory?  You can
change the cache directory by setting the PYTHON_EGG_CACHE environment
variable to point to an accessible directory. [/i]

Off course my profile has access to this directory and I suppose that something is going wrong with standalone python's global environment but I'm not sure. The same I'm getting for both versions 1.7 and 1.8

**Comment by bartbaas** [comment]
Hi, seems like a permission issue, python must run with administrator privileges. Please try to start cmd with administrator privileges (run as administrator) and see what happens.

**Comment by maraev** [comment]
I don't thik so. 
I've just set PYTHON_EGG_CACHE=C:\Users\maraev\AppData\Local\Temp (explanations here:  http://stackoverflow.com/questions/2192323/what-is-the-python-egg-cache-python-egg-cache)  and now getting bellow thing:
 MapProxy server running at http://localhost:8081/mapproxy
 Close this dialog to stop the server
No section: 'formatters'

**Comment by bartbaas** [comment]
I'm not able to reproduce your problem. If you found out what causes the issue, please send a pull request with the fix.
